apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: a305l0o3s-python-gitops
  description: This is GitOps manifest for a305l0o3s-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: a305l0o3s-python
    backstage.io/kubernetes-id: a305l0o3s-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:a305l0o3s-python
