apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a305l0o3s-python
  janus-idp.io/tekton: a305l0o3s-python
  backstage.io/kubernetes-id: a305l0o3s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a305l0o3s-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
