apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: a305l0o3s-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a305l0o3s-python 
  name: a305l0o3s-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: a305l0o3s-python 
